# You must include a `.env` file with the following content:
#   MYSQL_ROOT_PASSWORD=chooseapassword
#   MYSQL_PASSWORD=chooseapassword
#   MYSQL_HOST=chooseahost
#   PHP_DEBUG=1 or 0

version: '2'
services:
    smr-common:
        # Base configuration for `smr` (production) and `smr-dev` (testing).
        build:
            context: .
            args:
                - PHP_DEBUG=${PHP_DEBUG}
        ports:
            - "80:80"
        volumes:
            - smr_upload:/smr/htdocs/upload
            - ./config:/smr/config:ro

    smr:
        extends: smr-common
        # depends_on cannot be defined in extended services (i.e. smr-common)
        depends_on:
            - mysql
            - smtp

    smr-dev:
        extends: smr-common
        # depends_on cannot be defined in extended services (i.e. smr-common)
        depends_on:
            - mysql
            - smtp
        volumes:
            # Mount the source code instead of copying it.
            - ./admin:/smr/admin
            - ./engine:/smr/engine
            - ./htdocs:/smr/htdocs
            - ./lib:/smr/lib
            - ./templates:/smr/templates

    smtp:
        image: hemberger/postfix-relay
        environment:
            - OPENDKIM_DOMAINS=smrealms.de
            - OPENDKIM_SELECTOR=key1
        volumes:
            - ./opendkim:/etc/opendkim/keys/smrealms.de

    flyway:
        image: boxfuse/flyway:latest-alpine
        command: -url=jdbc:mysql://${MYSQL_HOST}/smr_live -user=smr -password=${MYSQL_PASSWORD} migrate
        depends_on:
            - mysql
        volumes:
            - ./db/patches:/flyway/sql:ro

    mysql:
        image: mysql:5.7
        container_name: ${MYSQL_HOST}
        # By using the default image, we must expose the secrets in
        # the runtime environment (because we can't specify build args).
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER:          smr
            MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
            MYSQL_DATABASE:      smr_live
        volumes:
            - smr_mysql_data:/var/lib/mysql
        # The mysql:5.7+ docker default sql mode uses STRICT_TRANS_TABLES,
        # which is incompatible with the way the SMR database is used.
        # Therefore, we override CMD to omit this sql mode.
        command: ["mysqld", "--sql-mode=NO_ENGINE_SUBSTITUTION"]


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        # Publish to port 8080
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql

    discord:
        build:
            context: .
            dockerfile: ./tools/discord/Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./config:/smr/config

    irc:
        build:
            context: .
            dockerfile: ./tools/irc/Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./config:/smr/config

    npc:
        build:
            context: .
            dockerfile: ./tools/npc/Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./config:/smr/config

    # Generate rich API documentation of the SMR source code.
    api-docs:
        build:
            context: .
            dockerfile: ./docs/Dockerfile
        ports:
            - "8081:80"

# We want persistent, anonymous data volumes
volumes:
    smr_upload:
    smr_mysql_data:
