version: '2'

services:
    smr-docs:
        image: nginx:alpine
        volumes:
            - ./api/html:/usr/share/nginx/html:ro
        ports:
            - "8081:80"

    phpdox:
        build:
            context: .
        volumes:
            # phpdox configuration file
            - ./phpdox.xml:/api/phpdox.xml:ro
            # Mount entire src code for git enricher
            - ../:/api/smr:ro
            # Mount phpdox output dir for access to html
            - ./api:/api:rw
